// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shkqquzpmbeqhpsugemi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoa3FxdXpwbWJlcWhwc3VnZW1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyOTgwODksImV4cCI6MjA3NDg3NDA4OX0.kUVEcNVNri-wJ-NUGSa8hiMhdmPVKoyEjyUIskgTZJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});