// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtzwlsmgjdfmazgxqgnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10endsc21namRmbWF6Z3hxZ25oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDc2MDksImV4cCI6MjA3MzAyMzYwOX0.PrECG0mvSdkXWNLDCg6N3UrmxtOYarSpoZA857Hrk6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});